version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      PORT: 3001
    ports:
      - '3001:3001'
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    container_name: frontend
    environment:
      API_URL: http://localhost:3001
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - backend

  admin:
    image: directus/directus:latest
    container_name: admin
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_PORT: ${POSTGRES_PORT}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '8055:8055'
    depends_on:
      - postgres